name: healthy_nutrition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-149.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  material_symbols_icons: ^4.2811.0
  camerawesome: ^2.3.0
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  multi_circular_slider: ^1.1.0
  table_calendar: ^3.2.0
  haptic_feedback: ^0.5.1+1
  pytorch_lite: ^4.3.2
  syncfusion_flutter_gauges: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/fire.png
