name: healthy_nutrition
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-149.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  material_symbols_icons: ^4.2811.0
  camera: ^0.11.1
  persistent_bottom_nav_bar: ^6.2.1
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  table_calendar: ^3.2.0
  haptic_feedback: ^0.5.1+1
  syncfusion_flutter_gauges: ^30.1.37
  blurrycontainer: ^2.1.0
  google_mlkit_image_labeling: ^0.14.1
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_launcher_icons: "^0.14.3"
  wheel_picker: ^0.2.1
  material_dialogs: ^1.1.5
  pie_chart: ^5.4.0
  flutter_phoenix: "^1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/fire.png
    - models/model_v1.tflite
    - test_models/model_unquant.tflite
    - test_models/my_model.tflite
    - test_models/labels.txt

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"

  android: "launcher_icon"
  # image_path_android: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "assets/icon/background.png"
  # adaptive_icon_foreground: "assets/icon/foreground.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  # image_path_ios: "assets/icons/icon.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true
